auth0:
  audience: http://localhost:5000
  domain: https://magnushodne.eu.auth0.com/
spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: POSTGRESQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/chat-app-db
    username: localDevUser
    password: localDevPassword
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: chat-app-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://magnushodne.eu.auth0.com/
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: https://magnushodne.eu.auth0.com/
server:
  port: 5000