spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            audience: ${AUTH0_AUDIENCE}
            client-id: ${AUTH0_CLIENT_ID}
            client-secret: ${AUTH0_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            issuer-uri: ${AUTH0_DOMAIN}
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_DOMAIN}
server:
  port: 5000