version: '3.1'
services:
  postgres-db:
    container_name: 'postgres-db-chat-app'
    image: postgres:alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}