@startuml
'https://plantuml.com/object-diagram

title Data model

object User {
    user_id: UUID **PK**
    ..
    sub: String
    username: String
    picture: String
    description: String
    created_at: Date
    updated_at: Date
    last_login: Date
}

object Server {
    server_id: UUID **PK**
    ..
    owner_id: UUID **FK**
    name: String
    created_at: Date
    updated_at: Date
}

object Channel {
    channel_id: UUID **PK**
    ..
    server_id: UUID **FK**
    name: String
    description: String
    created_at: Date
    updated_at: Date
}

object Message {
    message_id: UUID **PK**
    ..
    user_id: UUID **FK**
    channel_id: UUID **FK**
    content: String
    created_at: Date
    updated_at: Date
}

object server_user {
    server_id: UUID **FK**
    user_id: UUID **FK**
    ..
    created_at: Date
}


User "1" - "0..*" Server::user_id: owns
User "1" -- "0..*" Message::user_id
User "0..*" -- "0..*" Server::user_id: member of
Server "1" -- "1..*" Channel::server_id
Channel "1" -- "0..*" Message::channel_id

@enduml
